//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string LoginID { get; set; }
        public string Salt { get; set; }
        public int RoleID { get; set; }
        public byte[] HashedPassword { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Role Role { get; set; }
        public virtual Student Student { get; set; }
    }
}
