//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPade.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.Class_Assgn = new HashSet<Class_Assgn>();
            this.Submissions = new HashSet<Submission>();
        }
    
        public int AssignmentID { get; set; }
        public string Describe { get; set; }
        public int MaxAttempt { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Solution { get; set; }
        public string ModuleCode { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string DeletedBy { get; set; }
        public string AssgnTitle { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Hints { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_Assgn> Class_Assgn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission> Submissions { get; set; }
        public virtual Module Module { get; set; }
    }
}
