//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPade.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lec_Class
    {
        public string StaffID { get; set; }
        public int ClassID { get; set; }
        public int C_id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual Lecturer Lecturer1 { get; set; }
    }
}
